#index:
#    path: /
#    controller: App\Controller\DefaultController::index

pokefrontindex:
  path: /
  controller: App\Controller\PokemonFrontController::index

pokeindex:
  path: /admin
  controller: App\Controller\PokemonController::index
